Import('env')
Import('library')

unit_tests = env.Program('unit_tests', [Glob('units/*.cxx'), Glob('fixtures/*.cxx')], LIBS=[library, 'boost_thread-mt', 'pthread', 'boost_system-mt', 'protobuf', 'gmock', 'gtest'])
env.Alias('test', [unit_tests], unit_tests[0].path)
env.AlwaysBuild('test')
Return('unit_tests')
