language: cpp
compiler:
 - gcc
 - clang
script: scons
before_install:
 - sudo add-apt-repository -y ppa:boost-latest/ppa
 - sudo apt-get update -qq
 - sudo apt-get install -y libprotobuf-dev protobuf-compiler libboost$BOOST_VERSION-all-dev
env:
 - RIAK_CPP_BUILD_DEBUG=yes BOOST_VERSION=1.54
 - RIAK_CPP_BUILD_DEBUG=yes BOOST_VERSION=1.55
 - RIAK_CPP_BUILD_DEBUG=no  BOOST_VERSION=1.54
 - RIAK_CPP_BUILD_DEBUG=no  BOOST_VERSION=1.55
matrix:
  fast_finish: true