Import('env')
Import('library')

env = env.Clone(CPPPATH=["#tests", '#source'])

test_sources = ['all_tests.cxx', 'main.cxx', 'configuration.cxx']
unit_tests = env.Program('test', test_sources, INCLUDE=['library'], LIBS=['UnitTest++', library, 'boost_thread-mt', 'boost_program_options'])
env.Alias('test', [unit_tests])
env.AlwaysBuild('test')
Return('unit_tests')
